name: news_reader
description: A simple news reader that utilizes sql lite to save stories on your device.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  path: ^1.6.4
  sqflite: ^1.1.6
  dio: ^2.1.16
  json_annotation: ^3.0.0
  url_launcher: ^5.1.3
  cached_network_image: ^1.1.1
  flutter_cache_manager: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.2
  build_runner: ^1.7.0
  flutter_native_splash: ^0.1.7+2
  mockito: ^4.1.1

flutter:
  uses-material-design: true
